# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-bassoontracker

# >> macros
# << macros

Summary:    Bassoontracker
Version:    0.4.0
Release:    2
Group:      Qt/Qt
License:    MIT
BuildArch:  noarch
URL:        https://www.stef.be/bassoontracker/
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   libsailfishapp-launcher
Requires:   sailfish-components-webview-qt5

BuildRequires:  pkgconfig(sailfishapp) >= 1.0.3
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Bassoontracker is an Amiga style mod tracker for making music. https://www.stef.be/bassoontracker/

%if "%{?vendor}" == "chum"
PackageName: BassoonTracker
Type: desktop-application
Categories:
 - Audio
PackagerName: Mark Washeim (poetaster)
Custom:
 - Repo: https://github.com/poetaster/harbour-bassoontracker
Icon: https://raw.githubusercontent.com/poetaster/harbour-bassoontracker/main/icons/128x128/harbour-bassoontracker.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/BassoonTracker/1e868d9225727df951191bdd542c69cda243ab89/skin/screenshot.png
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(0644,root,root,-)
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
